/*
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JsonProjectUiModule extends AbstractJsonProjectUiModule {

	public JsonProjectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
