/**
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.jsonProject.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.jsonProject.jsonProject.JsonPrimitive;
import org.xtext.jsonProject.jsonProject.JsonProjectPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Json Primitive</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JsonPrimitiveImpl extends JsonObjectImpl implements JsonPrimitive
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsonPrimitiveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonProjectPackage.Literals.JSON_PRIMITIVE;
  }

} //JsonPrimitiveImpl
