/**
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.jsonProject.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.jsonProject.jsonProject.JsonObject;
import org.xtext.jsonProject.jsonProject.JsonProjectPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Json Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JsonObjectImpl extends MinimalEObjectImpl.Container implements JsonObject
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsonObjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonProjectPackage.Literals.JSON_OBJECT;
  }

} //JsonObjectImpl
