/**
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.jsonProject;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.jsonProject.jsonProject.JsonProjectFactory
 * @model kind="package"
 * @generated
 */
public interface JsonProjectPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jsonProject";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/jsonProject/JsonProject";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jsonProject";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JsonProjectPackage eINSTANCE = org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonCommandsImpl <em>Json Commands</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.JsonCommandsImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonCommands()
   * @generated
   */
  int JSON_COMMANDS = 0;

  /**
   * The feature id for the '<em><b>Json Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_COMMANDS__JSON_COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Json Commands</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_COMMANDS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonCommandImpl <em>Json Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.JsonCommandImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonCommand()
   * @generated
   */
  int JSON_COMMAND = 1;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_COMMAND__INIT = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_COMMAND__OPERATIONS = 1;

  /**
   * The feature id for the '<em><b>Final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_COMMAND__FINAL = 2;

  /**
   * The number of structural features of the '<em>Json Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_COMMAND_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.InitialisationImpl <em>Initialisation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.InitialisationImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getInitialisation()
   * @generated
   */
  int INITIALISATION = 2;

  /**
   * The feature id for the '<em><b>File Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALISATION__FILE_PATH = 0;

  /**
   * The number of structural features of the '<em>Initialisation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALISATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.OperationImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 3;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.InsertImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 4;

  /**
   * The feature id for the '<em><b>Json Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__JSON_OBJECT = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__PATH = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.PathImpl <em>Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.PathImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getPath()
   * @generated
   */
  int PATH = 5;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__VALUES = 0;

  /**
   * The number of structural features of the '<em>Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.ModifyImpl <em>Modify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.ModifyImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getModify()
   * @generated
   */
  int MODIFY = 6;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY__PATH = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Json Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY__JSON_OBJECT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Modify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.SumImpl <em>Sum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.SumImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getSum()
   * @generated
   */
  int SUM = 7;

  /**
   * The feature id for the '<em><b>Path TO Store</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM__PATH_TO_STORE = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Path To Add</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM__PATH_TO_ADD = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Sum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.RemoveImpl <em>Remove</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.RemoveImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getRemove()
   * @generated
   */
  int REMOVE = 8;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE__PATH = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Remove</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.MultImpl <em>Mult</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.MultImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getMult()
   * @generated
   */
  int MULT = 9;

  /**
   * The feature id for the '<em><b>Path TO Store</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__PATH_TO_STORE = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Path To Mult</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__PATH_TO_MULT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Mult</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.SelectImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 10;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__PATH = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.FinalImpl <em>Final</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.FinalImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getFinal()
   * @generated
   */
  int FINAL = 11;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL__PATH = 0;

  /**
   * The number of structural features of the '<em>Final</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.StoreImpl <em>Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.StoreImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getStore()
   * @generated
   */
  int STORE = 12;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__PATH = FINAL__PATH;

  /**
   * The feature id for the '<em><b>File Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__FILE_PATH = FINAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_FEATURE_COUNT = FINAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.PrintImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 13;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__PATH = FINAL__PATH;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = FINAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonObjectImpl <em>Json Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.JsonObjectImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonObject()
   * @generated
   */
  int JSON_OBJECT = 14;

  /**
   * The number of structural features of the '<em>Json Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_OBJECT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonPrimitiveImpl <em>Json Primitive</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.JsonPrimitiveImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonPrimitive()
   * @generated
   */
  int JSON_PRIMITIVE = 15;

  /**
   * The number of structural features of the '<em>Json Primitive</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_PRIMITIVE_FEATURE_COUNT = JSON_OBJECT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.ArrayObjectImpl <em>Array Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.ArrayObjectImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getArrayObject()
   * @generated
   */
  int ARRAY_OBJECT = 16;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_OBJECT__VALUES = JSON_PRIMITIVE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Array Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_OBJECT_FEATURE_COUNT = JSON_PRIMITIVE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.BooleanObjectImpl <em>Boolean Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.BooleanObjectImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getBooleanObject()
   * @generated
   */
  int BOOLEAN_OBJECT = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_OBJECT__VALUE = JSON_PRIMITIVE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_OBJECT_FEATURE_COUNT = JSON_PRIMITIVE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.StringObjectImpl <em>String Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.StringObjectImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getStringObject()
   * @generated
   */
  int STRING_OBJECT = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_OBJECT__VALUE = JSON_PRIMITIVE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_OBJECT_FEATURE_COUNT = JSON_PRIMITIVE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonEntriesImpl <em>Json Entries</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.JsonEntriesImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonEntries()
   * @generated
   */
  int JSON_ENTRIES = 19;

  /**
   * The feature id for the '<em><b>List Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ENTRIES__LIST_ENTRIES = JSON_OBJECT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Entries</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ENTRIES_FEATURE_COUNT = JSON_OBJECT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonEntryImpl <em>Json Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.impl.JsonEntryImpl
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonEntry()
   * @generated
   */
  int JSON_ENTRY = 20;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ENTRY__KEY = 0;

  /**
   * The feature id for the '<em><b>Json Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ENTRY__JSON_OBJECT = 1;

  /**
   * The number of structural features of the '<em>Json Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ENTRY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.jsonProject.jsonProject.Boolean <em>Boolean</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.jsonProject.jsonProject.Boolean
   * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 21;


  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.JsonCommands <em>Json Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Commands</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonCommands
   * @generated
   */
  EClass getJsonCommands();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.jsonProject.jsonProject.JsonCommands#getJsonCommands <em>Json Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Json Commands</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonCommands#getJsonCommands()
   * @see #getJsonCommands()
   * @generated
   */
  EReference getJsonCommands_JsonCommands();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.JsonCommand <em>Json Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Command</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonCommand
   * @generated
   */
  EClass getJsonCommand();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.JsonCommand#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonCommand#getInit()
   * @see #getJsonCommand()
   * @generated
   */
  EReference getJsonCommand_Init();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.jsonProject.jsonProject.JsonCommand#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonCommand#getOperations()
   * @see #getJsonCommand()
   * @generated
   */
  EReference getJsonCommand_Operations();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.JsonCommand#getFinal <em>Final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Final</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonCommand#getFinal()
   * @see #getJsonCommand()
   * @generated
   */
  EReference getJsonCommand_Final();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Initialisation <em>Initialisation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initialisation</em>'.
   * @see org.xtext.jsonProject.jsonProject.Initialisation
   * @generated
   */
  EClass getInitialisation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.jsonProject.jsonProject.Initialisation#getFilePath <em>File Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File Path</em>'.
   * @see org.xtext.jsonProject.jsonProject.Initialisation#getFilePath()
   * @see #getInitialisation()
   * @generated
   */
  EAttribute getInitialisation_FilePath();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.jsonProject.jsonProject.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see org.xtext.jsonProject.jsonProject.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Insert#getJsonObject <em>Json Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Json Object</em>'.
   * @see org.xtext.jsonProject.jsonProject.Insert#getJsonObject()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_JsonObject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Insert#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path</em>'.
   * @see org.xtext.jsonProject.jsonProject.Insert#getPath()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Path <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path</em>'.
   * @see org.xtext.jsonProject.jsonProject.Path
   * @generated
   */
  EClass getPath();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.jsonProject.jsonProject.Path#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see org.xtext.jsonProject.jsonProject.Path#getValues()
   * @see #getPath()
   * @generated
   */
  EAttribute getPath_Values();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Modify <em>Modify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modify</em>'.
   * @see org.xtext.jsonProject.jsonProject.Modify
   * @generated
   */
  EClass getModify();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Modify#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path</em>'.
   * @see org.xtext.jsonProject.jsonProject.Modify#getPath()
   * @see #getModify()
   * @generated
   */
  EReference getModify_Path();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Modify#getJsonObject <em>Json Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Json Object</em>'.
   * @see org.xtext.jsonProject.jsonProject.Modify#getJsonObject()
   * @see #getModify()
   * @generated
   */
  EReference getModify_JsonObject();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Sum <em>Sum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sum</em>'.
   * @see org.xtext.jsonProject.jsonProject.Sum
   * @generated
   */
  EClass getSum();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Sum#getPathTOStore <em>Path TO Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path TO Store</em>'.
   * @see org.xtext.jsonProject.jsonProject.Sum#getPathTOStore()
   * @see #getSum()
   * @generated
   */
  EReference getSum_PathTOStore();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Sum#getPathToAdd <em>Path To Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path To Add</em>'.
   * @see org.xtext.jsonProject.jsonProject.Sum#getPathToAdd()
   * @see #getSum()
   * @generated
   */
  EReference getSum_PathToAdd();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Remove <em>Remove</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Remove</em>'.
   * @see org.xtext.jsonProject.jsonProject.Remove
   * @generated
   */
  EClass getRemove();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Remove#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path</em>'.
   * @see org.xtext.jsonProject.jsonProject.Remove#getPath()
   * @see #getRemove()
   * @generated
   */
  EReference getRemove_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Mult <em>Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mult</em>'.
   * @see org.xtext.jsonProject.jsonProject.Mult
   * @generated
   */
  EClass getMult();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Mult#getPathTOStore <em>Path TO Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path TO Store</em>'.
   * @see org.xtext.jsonProject.jsonProject.Mult#getPathTOStore()
   * @see #getMult()
   * @generated
   */
  EReference getMult_PathTOStore();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Mult#getPathToMult <em>Path To Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path To Mult</em>'.
   * @see org.xtext.jsonProject.jsonProject.Mult#getPathToMult()
   * @see #getMult()
   * @generated
   */
  EReference getMult_PathToMult();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see org.xtext.jsonProject.jsonProject.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Select#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path</em>'.
   * @see org.xtext.jsonProject.jsonProject.Select#getPath()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Final <em>Final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Final</em>'.
   * @see org.xtext.jsonProject.jsonProject.Final
   * @generated
   */
  EClass getFinal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.Final#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path</em>'.
   * @see org.xtext.jsonProject.jsonProject.Final#getPath()
   * @see #getFinal()
   * @generated
   */
  EReference getFinal_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Store <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store</em>'.
   * @see org.xtext.jsonProject.jsonProject.Store
   * @generated
   */
  EClass getStore();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.jsonProject.jsonProject.Store#getFilePath <em>File Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File Path</em>'.
   * @see org.xtext.jsonProject.jsonProject.Store#getFilePath()
   * @see #getStore()
   * @generated
   */
  EAttribute getStore_FilePath();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see org.xtext.jsonProject.jsonProject.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.JsonObject <em>Json Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Object</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonObject
   * @generated
   */
  EClass getJsonObject();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.JsonPrimitive <em>Json Primitive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Primitive</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonPrimitive
   * @generated
   */
  EClass getJsonPrimitive();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.ArrayObject <em>Array Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Object</em>'.
   * @see org.xtext.jsonProject.jsonProject.ArrayObject
   * @generated
   */
  EClass getArrayObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.jsonProject.jsonProject.ArrayObject#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see org.xtext.jsonProject.jsonProject.ArrayObject#getValues()
   * @see #getArrayObject()
   * @generated
   */
  EReference getArrayObject_Values();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.BooleanObject <em>Boolean Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Object</em>'.
   * @see org.xtext.jsonProject.jsonProject.BooleanObject
   * @generated
   */
  EClass getBooleanObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.jsonProject.jsonProject.BooleanObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.jsonProject.jsonProject.BooleanObject#getValue()
   * @see #getBooleanObject()
   * @generated
   */
  EAttribute getBooleanObject_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.StringObject <em>String Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Object</em>'.
   * @see org.xtext.jsonProject.jsonProject.StringObject
   * @generated
   */
  EClass getStringObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.jsonProject.jsonProject.StringObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.jsonProject.jsonProject.StringObject#getValue()
   * @see #getStringObject()
   * @generated
   */
  EAttribute getStringObject_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.JsonEntries <em>Json Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Entries</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonEntries
   * @generated
   */
  EClass getJsonEntries();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.jsonProject.jsonProject.JsonEntries#getListEntries <em>List Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List Entries</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonEntries#getListEntries()
   * @see #getJsonEntries()
   * @generated
   */
  EReference getJsonEntries_ListEntries();

  /**
   * Returns the meta object for class '{@link org.xtext.jsonProject.jsonProject.JsonEntry <em>Json Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Entry</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonEntry
   * @generated
   */
  EClass getJsonEntry();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.jsonProject.jsonProject.JsonEntry#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonEntry#getKey()
   * @see #getJsonEntry()
   * @generated
   */
  EAttribute getJsonEntry_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.jsonProject.jsonProject.JsonEntry#getJsonObject <em>Json Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Json Object</em>'.
   * @see org.xtext.jsonProject.jsonProject.JsonEntry#getJsonObject()
   * @see #getJsonEntry()
   * @generated
   */
  EReference getJsonEntry_JsonObject();

  /**
   * Returns the meta object for enum '{@link org.xtext.jsonProject.jsonProject.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Boolean</em>'.
   * @see org.xtext.jsonProject.jsonProject.Boolean
   * @generated
   */
  EEnum getBoolean();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JsonProjectFactory getJsonProjectFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonCommandsImpl <em>Json Commands</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.JsonCommandsImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonCommands()
     * @generated
     */
    EClass JSON_COMMANDS = eINSTANCE.getJsonCommands();

    /**
     * The meta object literal for the '<em><b>Json Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_COMMANDS__JSON_COMMANDS = eINSTANCE.getJsonCommands_JsonCommands();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonCommandImpl <em>Json Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.JsonCommandImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonCommand()
     * @generated
     */
    EClass JSON_COMMAND = eINSTANCE.getJsonCommand();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_COMMAND__INIT = eINSTANCE.getJsonCommand_Init();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_COMMAND__OPERATIONS = eINSTANCE.getJsonCommand_Operations();

    /**
     * The meta object literal for the '<em><b>Final</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_COMMAND__FINAL = eINSTANCE.getJsonCommand_Final();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.InitialisationImpl <em>Initialisation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.InitialisationImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getInitialisation()
     * @generated
     */
    EClass INITIALISATION = eINSTANCE.getInitialisation();

    /**
     * The meta object literal for the '<em><b>File Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INITIALISATION__FILE_PATH = eINSTANCE.getInitialisation_FilePath();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.OperationImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.InsertImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '<em><b>Json Object</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__JSON_OBJECT = eINSTANCE.getInsert_JsonObject();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__PATH = eINSTANCE.getInsert_Path();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.PathImpl <em>Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.PathImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getPath()
     * @generated
     */
    EClass PATH = eINSTANCE.getPath();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATH__VALUES = eINSTANCE.getPath_Values();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.ModifyImpl <em>Modify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.ModifyImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getModify()
     * @generated
     */
    EClass MODIFY = eINSTANCE.getModify();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODIFY__PATH = eINSTANCE.getModify_Path();

    /**
     * The meta object literal for the '<em><b>Json Object</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODIFY__JSON_OBJECT = eINSTANCE.getModify_JsonObject();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.SumImpl <em>Sum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.SumImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getSum()
     * @generated
     */
    EClass SUM = eINSTANCE.getSum();

    /**
     * The meta object literal for the '<em><b>Path TO Store</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUM__PATH_TO_STORE = eINSTANCE.getSum_PathTOStore();

    /**
     * The meta object literal for the '<em><b>Path To Add</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUM__PATH_TO_ADD = eINSTANCE.getSum_PathToAdd();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.RemoveImpl <em>Remove</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.RemoveImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getRemove()
     * @generated
     */
    EClass REMOVE = eINSTANCE.getRemove();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REMOVE__PATH = eINSTANCE.getRemove_Path();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.MultImpl <em>Mult</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.MultImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getMult()
     * @generated
     */
    EClass MULT = eINSTANCE.getMult();

    /**
     * The meta object literal for the '<em><b>Path TO Store</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__PATH_TO_STORE = eINSTANCE.getMult_PathTOStore();

    /**
     * The meta object literal for the '<em><b>Path To Mult</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__PATH_TO_MULT = eINSTANCE.getMult_PathToMult();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.SelectImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__PATH = eINSTANCE.getSelect_Path();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.FinalImpl <em>Final</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.FinalImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getFinal()
     * @generated
     */
    EClass FINAL = eINSTANCE.getFinal();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FINAL__PATH = eINSTANCE.getFinal_Path();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.StoreImpl <em>Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.StoreImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getStore()
     * @generated
     */
    EClass STORE = eINSTANCE.getStore();

    /**
     * The meta object literal for the '<em><b>File Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE__FILE_PATH = eINSTANCE.getStore_FilePath();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.PrintImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonObjectImpl <em>Json Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.JsonObjectImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonObject()
     * @generated
     */
    EClass JSON_OBJECT = eINSTANCE.getJsonObject();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonPrimitiveImpl <em>Json Primitive</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.JsonPrimitiveImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonPrimitive()
     * @generated
     */
    EClass JSON_PRIMITIVE = eINSTANCE.getJsonPrimitive();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.ArrayObjectImpl <em>Array Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.ArrayObjectImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getArrayObject()
     * @generated
     */
    EClass ARRAY_OBJECT = eINSTANCE.getArrayObject();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_OBJECT__VALUES = eINSTANCE.getArrayObject_Values();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.BooleanObjectImpl <em>Boolean Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.BooleanObjectImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getBooleanObject()
     * @generated
     */
    EClass BOOLEAN_OBJECT = eINSTANCE.getBooleanObject();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_OBJECT__VALUE = eINSTANCE.getBooleanObject_Value();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.StringObjectImpl <em>String Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.StringObjectImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getStringObject()
     * @generated
     */
    EClass STRING_OBJECT = eINSTANCE.getStringObject();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_OBJECT__VALUE = eINSTANCE.getStringObject_Value();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonEntriesImpl <em>Json Entries</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.JsonEntriesImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonEntries()
     * @generated
     */
    EClass JSON_ENTRIES = eINSTANCE.getJsonEntries();

    /**
     * The meta object literal for the '<em><b>List Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_ENTRIES__LIST_ENTRIES = eINSTANCE.getJsonEntries_ListEntries();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.impl.JsonEntryImpl <em>Json Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.impl.JsonEntryImpl
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getJsonEntry()
     * @generated
     */
    EClass JSON_ENTRY = eINSTANCE.getJsonEntry();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_ENTRY__KEY = eINSTANCE.getJsonEntry_Key();

    /**
     * The meta object literal for the '<em><b>Json Object</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_ENTRY__JSON_OBJECT = eINSTANCE.getJsonEntry_JsonObject();

    /**
     * The meta object literal for the '{@link org.xtext.jsonProject.jsonProject.Boolean <em>Boolean</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.jsonProject.jsonProject.Boolean
     * @see org.xtext.jsonProject.jsonProject.impl.JsonProjectPackageImpl#getBoolean()
     * @generated
     */
    EEnum BOOLEAN = eINSTANCE.getBoolean();

  }

} //JsonProjectPackage
