/**
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.jsonProject;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Primitive</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.jsonProject.jsonProject.JsonProjectPackage#getJsonPrimitive()
 * @model
 * @generated
 */
public interface JsonPrimitive extends JsonObject
{
} // JsonPrimitive
