/**
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.jsonProject;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.jsonProject.jsonProject.Sum#getPathTOStore <em>Path TO Store</em>}</li>
 *   <li>{@link org.xtext.jsonProject.jsonProject.Sum#getPathToAdd <em>Path To Add</em>}</li>
 * </ul>
 *
 * @see org.xtext.jsonProject.jsonProject.JsonProjectPackage#getSum()
 * @model
 * @generated
 */
public interface Sum extends Operation
{
  /**
   * Returns the value of the '<em><b>Path TO Store</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path TO Store</em>' containment reference.
   * @see #setPathTOStore(Path)
   * @see org.xtext.jsonProject.jsonProject.JsonProjectPackage#getSum_PathTOStore()
   * @model containment="true"
   * @generated
   */
  Path getPathTOStore();

  /**
   * Sets the value of the '{@link org.xtext.jsonProject.jsonProject.Sum#getPathTOStore <em>Path TO Store</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path TO Store</em>' containment reference.
   * @see #getPathTOStore()
   * @generated
   */
  void setPathTOStore(Path value);

  /**
   * Returns the value of the '<em><b>Path To Add</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path To Add</em>' containment reference.
   * @see #setPathToAdd(Path)
   * @see org.xtext.jsonProject.jsonProject.JsonProjectPackage#getSum_PathToAdd()
   * @model containment="true"
   * @generated
   */
  Path getPathToAdd();

  /**
   * Sets the value of the '{@link org.xtext.jsonProject.jsonProject.Sum#getPathToAdd <em>Path To Add</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path To Add</em>' containment reference.
   * @see #getPathToAdd()
   * @generated
   */
  void setPathToAdd(Path value);

} // Sum
