/*
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.jsonProject.services.JsonProjectGrammarAccess;

@SuppressWarnings("all")
public class JsonProjectSyntacticSequencer extends AbstractSyntacticSequencer {

	protected JsonProjectGrammarAccess grammarAccess;
	protected AbstractElementAlias match_JsonPrimitive_NULLTerminalRuleCall_2_1_or_NumberObjectParserRuleCall_4_1;
	protected AbstractElementAlias match_Path_GOBACKTerminalRuleCall_1_1_or_ROOTTerminalRuleCall_1_2;
	protected AbstractElementAlias match_Path___FullStopKeyword_2_0_GOBACKTerminalRuleCall_2_1_1__a;
	protected AbstractElementAlias match_Path___GOBACKTerminalRuleCall_2_1_1_FullStopKeyword_2_0__a;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (JsonProjectGrammarAccess) access;
		match_JsonPrimitive_NULLTerminalRuleCall_2_1_or_NumberObjectParserRuleCall_4_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getJsonPrimitiveAccess().getNULLTerminalRuleCall_2_1()), new TokenAlias(false, false, grammarAccess.getJsonPrimitiveAccess().getNumberObjectParserRuleCall_4_1()));
		match_Path_GOBACKTerminalRuleCall_1_1_or_ROOTTerminalRuleCall_1_2 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getPathAccess().getGOBACKTerminalRuleCall_1_1()), new TokenAlias(false, false, grammarAccess.getPathAccess().getROOTTerminalRuleCall_1_2()));
		match_Path___FullStopKeyword_2_0_GOBACKTerminalRuleCall_2_1_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getPathAccess().getFullStopKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getPathAccess().getGOBACKTerminalRuleCall_2_1_1()));
		match_Path___GOBACKTerminalRuleCall_2_1_1_FullStopKeyword_2_0__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getPathAccess().getGOBACKTerminalRuleCall_2_1_1()), new TokenAlias(false, false, grammarAccess.getPathAccess().getFullStopKeyword_2_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getGOBACKRule())
			return getGOBACKToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getNULLRule())
			return getNULLToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getNumberObjectRule())
			return getNumberObjectToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getROOTRule())
			return getROOTToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal GOBACK : '?';
	 */
	protected String getGOBACKToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "?";
	}
	
	/**
	 * terminal NULL:
	 * 	'null'
	 * ;
	 */
	protected String getNULLToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "null";
	}
	
	/**
	 * NumberObject:
	 * 	(INT | DOUBLE)
	 * ;
	 */
	protected String getNumberObjectToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	/**
	 * terminal ROOT : '$';
	 */
	protected String getROOTToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "$";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_JsonPrimitive_NULLTerminalRuleCall_2_1_or_NumberObjectParserRuleCall_4_1.equals(syntax))
				emit_JsonPrimitive_NULLTerminalRuleCall_2_1_or_NumberObjectParserRuleCall_4_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Path_GOBACKTerminalRuleCall_1_1_or_ROOTTerminalRuleCall_1_2.equals(syntax))
				emit_Path_GOBACKTerminalRuleCall_1_1_or_ROOTTerminalRuleCall_1_2(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Path___FullStopKeyword_2_0_GOBACKTerminalRuleCall_2_1_1__a.equals(syntax))
				emit_Path___FullStopKeyword_2_0_GOBACKTerminalRuleCall_2_1_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Path___GOBACKTerminalRuleCall_2_1_1_FullStopKeyword_2_0__a.equals(syntax))
				emit_Path___GOBACKTerminalRuleCall_2_1_1_FullStopKeyword_2_0__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     NULL | NumberObject
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_JsonPrimitive_NULLTerminalRuleCall_2_1_or_NumberObjectParserRuleCall_4_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     GOBACK | ROOT
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '.' (GOBACK '.')* values+=ID
	 *     (rule start) (ambiguity) ('.' GOBACK)* (rule start)
	 */
	protected void emit_Path_GOBACKTerminalRuleCall_1_1_or_ROOTTerminalRuleCall_1_2(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('.' GOBACK)*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (GOBACK | ROOT) (ambiguity) (rule start)
	 *     values+=ID (ambiguity) (rule end)
	 */
	protected void emit_Path___FullStopKeyword_2_0_GOBACKTerminalRuleCall_2_1_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (GOBACK '.')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (GOBACK | ROOT) '.' (ambiguity) values+=ID
	 *     values+=ID '.' (ambiguity) values+=ID
	 */
	protected void emit_Path___GOBACKTerminalRuleCall_2_1_1_FullStopKeyword_2_0__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
