/*
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JsonProjectStandaloneSetup extends JsonProjectStandaloneSetupGenerated {

	public static void doSetup() {
		new JsonProjectStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
