/*
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.jsonProject.JsonProjectRuntimeModule;
import org.xtext.jsonProject.JsonProjectStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JsonProjectIdeSetup extends JsonProjectStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JsonProjectRuntimeModule(), new JsonProjectIdeModule()));
	}
	
}
