/*
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.ide;


/**
 * Use this class to register ide components.
 */
public class JsonProjectIdeModule extends AbstractJsonProjectIdeModule {
}
