/*
 * generated by Xtext 2.25.0
 */
package org.xtext.jsonProject.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.jsonProject.parser.antlr.internal.InternalJsonProjectParser;
import org.xtext.jsonProject.services.JsonProjectGrammarAccess;

public class JsonProjectParser extends AbstractAntlrParser {

	@Inject
	private JsonProjectGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJsonProjectParser createParser(XtextTokenStream stream) {
		return new InternalJsonProjectParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JsonCommands";
	}

	public JsonProjectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JsonProjectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
